### ISSUE TITLE
Issue with AGREE "Generate Simulink Models" Option

### ISSUE THREAD

**Issue by janetlj** [loonwerks/AGREE#77]
Build instance model failed when invoking the "Generate Simulink Models" option in AGREE's menu, throwing exception about error while re-instantiating the model.

The problem occurs with InstantiateModel.buildInstanceModelFile invocation at line 126 of https://github.com/loonwerks/AGREE/blob/master/com.rockwellcollins.atc.agree.codegen/src/com/rockwellcollins/atc/agree/codegen/handlers/MATLABFunctionHandler.java

**Comment by kfhoech** [comment]
This problem likely began occurring when OSATE removed it's own ResourceSet from the OSATE core code.  Since we create an ephemeral component implementation in a transactional editing domain, the ephemeral component instance is in a different resource set confined in the editing domain.  Then when the call into the OSATE code to create the ephemeral component instance from the ephemeral component implementation, it cannot see into the editing domain to load the ephemeral component implementation.  Thus, the call to create the ephemeral component instance fails.

It seems the correct solution is to expand our utility library for creation of ephemeral components to include methods to create ephemeral instances as well as ephemeral implementations.  A little refactoring to minimize technical debt by making the editing domain management common across the creation of various ephemeral component implementations and instances seems appropriate.

**Comment by kfhoech** [comment]
Resolved by pull request #78.
